line-length = 88
indent-width = 4

[lint]
extend-select = [
  "A",
  "ANN",
  "ARG",
  "ASYNC",
  "C90",
  "CPY",
  "EM",
  "EXE",
  "FBT",
  "FURB",
  "G",
  "ICN",
  "INP",
  "LOG",
  "N",
  "PERF",
  "PGH",
  "PLC",
  "PLE",
  "PLW",
  "PT",
  "PTH",
  "PYI",
  "Q",
  "RET",
  "RSE",
  "S",
  "SLF",
  "SLOT",
  "T20",
  "TC",
  "TID",
  "TD",
  "FIX",
  "TRY",
  "B",
  "C4",
  "SIM",
  "UP",
  "RUF",
]

ignore = ["E501", "ANN401", "ISC001", "W191"]

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"src/**/*.py" = ["T20"]
"tests/**/*.py" = ["S101", "ANN201", "ANN202", "CPY001"]
"__init__.py" = ["F401"]

[lint.pycodestyle]
max-doc-length = 72

[lint.flake8-copyright]
author = "Lenhard Hailar"
notice-rgx = "(?i)Copyright \\(C\\) \\d{4}"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = 72
